from opensearch_client import opensearch_vector_store


def test_aggregations_search():
    fields_to_test = [
        "accession_number",
        "api_link",
        "api_model",
        "ark",
        "box_name",
        "box_number",
        "catalog_key",
        "collection.id",
        "collection.title.keyword",
        "contributor.id",
        "contributor.facet",
        "contributor.label.keyword",
        "contributor.label_with_role",
        "contributor.role",
        "contributor.variants",
        "create_date",
        "creator.id",
        "creator.facet",
        "creator.variants",
        "csv_metadata_update_jobs",
        "date_created",
        "embedding_model",
        "embedding_text_length",
        "folder_name",
        "folder_number",
        "genre.id",
        "genre.facet",
        "genre.variants",
        "id",
        "identifier",
        "iiif_manifest",
        "indexed_at",
        "ingest_project.id",
        "ingest_project.title",
        "ingest_sheet.id",
        "ingest_sheet.title",
        "keywords",
        "language.id",
        "language.facet",
        "language.variants",
        "legacy_identifier",
        "library_unit",
        "license.id",
        "location.id",
        "location.facet",
        "location.variants",
        "modified_date",
        "notes.note",
        "notes.type",
        "physical_description_material",
        "physical_description_size",
        "preservation_level",
        "project.desc",
        "project.cycle",
        "project.manager",
        "project.name",
        "project.proposer",
        "project.task_number",
        "provenance",
        "published",
        "publisher",
        "related_url.url",
        "related_url.label",
        "representative_file_set.aspect_ratio",
        "representative_file_set.id",
        "representative_file_set.url",
        "rights_holder",
        "rights_statement.id",
        "rights_statement.label.keyword",
        "scope_and_contents",
        "series",
        "source",
        "status",
        "style_period.id",
        "style_period.facet",
        "style_period.label.keyword",
        "style_period.variants",
        "subject.id",
        "subject.facet",
        "subject.label.keyword",
        "subject.label_with_role",
        "subject.role",
        "subject.variants",
        "table_of_contents",
        "technique.id",
        "technique.facet",
        "technique.label.keyword",
        "technique.variants",
        "terms_of_use",
        "thumbnail",
        "title.keyword",
        "visibility",
        "work_type"
    ]
    
    for field in fields_to_test:
        try:
            print(f"Testing {field}:")
            result = opensearch_vector_store.aggregations_search(field)
            print(f"{field}: {result}")
        except Exception as e:
            print(f"An error occurred in {field} Aggregation: {e}")


if __name__ == "__main__":
    test_aggregations_search()
